# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf07af9f4c99ff598d770408659edb8c60c8b84f8ed1786d3d8519ddff8179bfefed73fbebe514d5666172587af9828fc2dbad7ca7ea4c210011dbd519a5521

test:
  secret_key_base: 98057db73441ed04a02119cabf810a8cc50d7006f896c979f9107ccb0183de02497c216bb9c589a13eb027f9527ead099ff1a3024a4fbcebf7285405355aa85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
